### ISSUE TITLE
Еще полезная доработка ORM

### ISSUE THREAD

**Issue by kerbylav** [livestreet/livestreet-framework#102]
Некий аналог GetXXXAdditionalData для ORM-сущностей, т.е. возможность массовой загрузки связанных данных для коллекции сущностей, без того, чтобы для каждой сущности делать отдельные запросы к БД

**Comment by mzhelskiy** [comment]
так есть же "#with"?

**Comment by kerbylav** [comment]
Ммм. А оно делает что-то подобное, да? а что-нибудь описание-подобного еще нет?

**Comment by mzhelskiy** [comment]
Честно, думал об этом все знают, т.к. эта штука работает еще c 1.0.3 :)
В фильтре можно передать имена принудительно загружаемых связей: ``'#with'=>array('user','topic')`` + можно передавать условия типа ``'#with'=>array('user'=>array('active'=>1),'topic')``

**Comment by kerbylav** [comment]
Жестко... :)
