### ISSUE TITLE
Исправить ModuleValidate_EntityValidatorDate

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#110]
Исправить
```php
            $iTimestamp = DateTimeParser::parse($sValue, $sFormat,
                array('month' => 1, 'day' => 1, 'hour' => 0, 'minute' => 0, 'second' => 0));
```
https://github.com/livestreet/livestreet-framework/blob/master/classes/modules/validate/entity/ValidatorDate.entity.class.php#L73-L74
на
```php
            $iTimestamp = DateTimeParser::parse($sValue, $sFormat);
```
потому что сбивает с толку. В описании метода `parse` как раз указано что нужно их задавать т.к. будут учитываться текущие (ЧЧ ММ СС), но по коду стает ясно что это не так (ох и лапша):
```php
		if(
			!isset($hour) && !isset($minute) && !isset($second)
			&& !isset($defaults['hour']) && !isset($defaults['minute']) && !isset($defaults['second'])
		)
			$hour=$minute=$second=0;
		else
		{
			if(!isset($hour))
				$hour=isset($defaults['hour']) ? $defaults['hour'] : date('H');
			if(!isset($minute))
				$minute=isset($defaults['minute']) ? $defaults['minute'] : date('i');
			if(!isset($second))
				$second=isset($defaults['second']) ? $defaults['second'] : date('s');
			$hour=(int)$hour;
			$minute=(int)$minute;
			$second=(int)$second;
		}
```
как видим, если их не задать, то будут 0 автоматически ровно также как они и заданы сейчас. 

Видимо, комментарий к методу был сделан для предыдущих версий метода или ошибочно кем-то написан, но суть такая: **все задает формат в сущности валидатора ($pattern в методе `parse` самого DateTimeParser), поэтому ручное управление и выставление `array('month' => 1, 'day' => 1, 'hour' => 0, 'minute' => 0, 'second' => 0)` путает т.к. ничего не меняет**.

А сбивает то, что как будто они жестко отключены и невозможны в формате (например, если нужен формат `'yyyy-MM-dd h:m:s'`)

Если не понятно изложено
---

Просто удалить тот параметр, он не меняет ровным счетом ничего т.к. передаваемый формат даты сам задает все что нужно.

**Comment by mzhelskiy** [comment]
Для валидации, да, разницы нет, а для возвращаемого значения timestamp есть
