### ISSUE TITLE
Хуки плагинов не загружаются

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#114]
На самом деле я не знаю как назвать таск, т.к. тут ситуация "сам себя укусил за хвост".

Итак:

- Админка не загружает данные, структуру главного конфига и все остальное
- Потому что конфиги плагинов не загружаются
- Не загружаются потому что не срабатывает автолоад модулей на старте как нужно
```php
// Какие модули должны быть загружены на старте
$config['module']['autoLoad'] = array('Hook', 'Cache', 'Logger', 'Security', 'Session', 'Lang', 'Message');
```
- Не срабатывает автолоад потому что движок инициализируется в порядке:
```php
    /**
     * Инициализация ядра движка
     * todo: запретить выполнять повторную инициализацию
     */
    public function Init()
    {
        /**
         * Загружаем плагины
         */
        $this->LoadPlugins();
        /**
         * Инициализируем хуки
         */
        $this->InitHooks();
        /**
         * Загружаем модули автозагрузки
         */
        $this->LoadModules();
....
```
- и до авто загрузки модулей на старте идет инициализация хуков
```php
    /**
     * Регистрирует хуки из /classes/hooks/
     *
     */
    protected function InitHooks()
    {
        $sDirHooks = Config::Get('path.application.server') . '/classes/hooks/';
        $aFiles = glob($sDirHooks . 'Hook*.class.php');

        if ($aFiles and count($aFiles)) {
            foreach ($aFiles as $sFile) {
                if (preg_match("/Hook([^_]+)\.class\.php$/i", basename($sFile), $aMatch)) {
                    //require_once($sFile);
                    $sClassName = 'Hook' . $aMatch[1];
                    $oHook = new $sClassName;
                    $oHook->RegisterHook();
                }
            }
        }

        /**
         * Подгружаем хуки активных плагинов
         */
        $this->InitPluginHooks();
    }
```
которая загружает сначала хуки приложения, после - плагинов. В приложении есть хук `HookStatisticsPerformance`, который регистрирует хук с проверкой на админа:
```php
        if ($this->User_GetIsAdmin()) {
            $this->AddHook('template_body_end', 'Statistics', __CLASS__, -1000);
        }
```
при этом идет загрузка модуля `user` когда другие модули ещё не загружены, модуль юзера на ините старается найти текущего, загружает его сущность, сущность при создании объекта хочет получить *красивую текстовку* для валидации :
```php
    /**
     * Определяем дополнительные правила валидации
     *
     * @param array|bool $aParam
     */
    public function __construct($aParam = false)
    {
        $this->aValidateRules[] = array(
            'password',
            'string',
            'allowEmpty' => false,
            'min'        => 5,
            'on'         => array('registration'),
            'label'      => $this->Lang_Get('auth.labels.password')
        );
```
и запускает инициализацию языкового модуля, который **должен был быть загружен автолоадом ПОСЛЕ инициализации и загрузки хуков плагинов**. При инициализации языкового модуля тот запускает хук `lang_init_start` когда на него обработчики не были повешены плагинами т.к. цепочка загрузки хуков до плагинов не дошла.

Админка не запускается, *ничего не работает*.

Особняком от админки фреймворк может делать такое (ура, гибкость), в этом нет ничего плохого, но:

1. нужно либо отказаться от идеи получения текстовок для любой сущности при создании объекта (весьма странно, как же их получать?)
2. либо ввести новый *тайный* хук строго для админки, который точно не будет пропущен (но ситуация может изменится в будущем и случиться когда-нибудь тоже самое снова)
3. либо наиболее правильное решение - при инициализации ядра инициализацию хуков
```php
        /**
         * Инициализируем хуки
         */
        $this->InitHooks();
```
опустить ниже авто загрузки модулей:
```php
    /**
     * Инициализация ядра движка
     * todo: запретить выполнять повторную инициализацию
     */
    public function Init()
    {
        /**
         * Загружаем плагины
         */
        $this->LoadPlugins();
        /**
         * Загружаем модули автозагрузки
         */
        $this->LoadModules();
        /**
         * Инициализируем хуки
         */
        $this->InitHooks();
        /**
         * Инициализируем загруженные модули
         */
        $this->InitModules();
        /**
         * Инициализируем загруженные плагины
         */
        $this->InitPlugins();
        /**
         * Запускаем хуки для события завершения инициализации Engine
         */
        $this->Hook_Run('engine_init_complete');
    }
```
чтобы гарантировано знать что автолоад модулей выполнился. Но в таком случае у хуков появляется меньше свобод и влияния на работу автозагружаемых модулей при старте, хотя по сути кроме кеширования там нечего-то и настраивать. Но для кеширования ранее настройки уже исправили (модуль повторно просто переинициализуется, хотя и тут вопрос были ли к кешу обращения до загрузки настроек админки)

Третий вариант вполне хороший и рабочий, но немного сужает потенциальные возможности хуков. И как не крути, чем-то пожертвовать нужно.

**Comment by mzhelskiy** [comment]
fix https://github.com/livestreet/livestreet-framework/commit/dd15b180d9ec0557423387765dc6bdcc27da6c96
