### ISSUE TITLE
Переименовать метод

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#116]
https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/Router.class.php#L284

`public function LoadConfig()`

по логике на что-то вроде `public function LoadRouterConfig()`

**Comment by mzhelskiy** [comment]
Логика спорна, т.к. по ней потребуется переименовать метод AssignVars  в AssignRouterVars и т.п.
Метод находится внутри класса Router и загружает конфиг роутера.
