### ISSUE TITLE
Исправить логику работы орм с методами Get[Entity]ItemsByArray[Field]

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#122]
О чем речь
---

В ORM ЛС есть два способа (виртуальных метода) для получения объектов по полю (в данном примере - "ид"):
- `Get[Entity]ItemsByIdIn`
- `Get[Entity]ItemsByArrayId`

Оба способа являются полными синонимами. На самом деле  `Get[Entity]ItemsByArrayId` является оберткой над `Get[Entity]ItemsByIdIn`:

https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/ModuleORM.class.php#L1122-L1127
```php
/**
 * getUserItemsByArrayId() get_user_items_by_array_id
 */
if (preg_match("@^get_([a-z]+)_items_by_array_([_a-z]+)$@i", $sNameUnderscore, $aMatch)) {
    return $this->GetItemsByArray(array($aMatch[2] => $aArgs[0]), $sEntityName);
}
```

https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/ModuleORM.class.php#L824-L840
```php
    /**
     * Возвращает список сущностей по фильтру
     * В качестве ключей возвращаемого массива используется primary key сущности
     *
     * @param array $aFilter Фильтр
     * @param string|null $sEntityFull Название класса сущности
     * @return array
     */
    public function GetItemsByArray($aFilter, $sEntityFull = null)
    {
        foreach ($aFilter as $k => $v) {
            $aFilter["{$k} IN"] = $v;
            unset($aFilter[$k]);
        }
        $aFilter[] = '#index-from-primary';
        return $this->GetItemsByFilter($aFilter, $sEntityFull);
    }
```

Проблема
---
- В `Get[Entity]ItemsByIdIn` идет получение сущностей если их `Id` (поле) указано в множестве (параметре-массиве). Но в параметре могут быть указаны ид, которых сущностей с этими ид нет в таблице и такой метод вернет только найденные сущности из указанного списка ид. В этом нет проблемы и все логично.

- Но работа метода `Get[Entity]ItemsByArrayId` в связи с логикой именования ожидается совсем по-другому: жесткое получение сущностей по указанному списку ид, без исключений: все или ничего. Но метод является лишь оберткой над предыдущим методом и делает не то, что ожидается.

Задача
---
Нужно переделать работу методов `Get[Entity]ItemsByArray[Field]` (конкретно - ф-я `public function GetItemsByArray`) таким образом, чтобы тот возвращал все указанные по значению поля сущности **или ничего**. Т.е. сделать прослойку в которой сравнивать поданное количество ид с ид полученных сущностей, если совпало - возвращать сущности, если нет - `array()`.

P.S. Надоело её обходить полу-решениями.

**Comment by mzhelskiy** [comment]
Делает он именно, то что ожидается - возвращает список сущностей по их ID с проставлением в качестве ключей массива id сущностей.
ItemsByArrayId появился за долго до  ItemsByIdIn, далее он был оптимизирован как враппер к ItemsByIdIn с параметром ``#index-from-primary`` (не полный синоним)

**Comment by psnet** [comment]
В корне не согласен.

**Comment by psnet** [comment]
Перечитай ещё раз описание. Зачем два метода лепить полу-однаковых?

**Comment by psnet** [comment]
>Делает он именно, то что ожидается - возвращает список сущностей по их ID с проставлением в качестве ключей массива id сущностей.

Ключи пока трогать не будем, я за них ничего не говорю. Суть в том, что по логике своего именования, которая гласит что **по точно переданному списку ид получит все объекты**, причем про ключи ничего не сказано. Если всех объектов нет - вернуть пустой массив.

Тут либо имя метода совершенно другое нужно дать либо переделать.

Если нужны ключи с полями, то всегда можно `#index-from` для IN.

**Comment by mzhelskiy** [comment]
> Зачем два метода лепить полу-однаковых?

Выше уже писал, повторю: изначально был метод ItemsByArrayId (он и в 1.0 есть), который возвращал список объектов по их ID с нужными ключами. После появления ItemsByIdIn код был оптимизирован.

**Comment by psnet** [comment]
>Выше уже писал, повторю: изначально был метод ItemsByArrayId (он и в 1.0 есть)

я знаю что он был изначально, он работает не так как надо. Но:

- ItemsByIdIn - получить из списка ид **то, что есть**
- ItemsByArrayId - получить **все** из указанного списка, **все или ничего**, все ли ид корректны и объекты существуют.

**Comment by psnet** [comment]
>изначально был метод ItemsByArrayId

да, он был давно, но это не отменяет того, что по его имени ожидается жестка системная работа "получить строго все".

**Comment by mzhelskiy** [comment]
> но это не отменяет того, что по его имени ожидается жестка системная работа "получить строго все".

у нас разные ожидания от названия )

**Comment by psnet** [comment]
Посмотри сам: зачем два разных метода:

- ByIdIn - входит в множество
- ByArrayId - строгое точное ограничение - массив ид
