### ISSUE TITLE
Непонятная логика в компонентах с переменными

### ISSUE THREAD

**Issue by mzhelskiy** [livestreet/livestreet-framework#124]
Для примера у компонента dropdown не все переменные переводятся из локальных https://github.com/livestreet/livestreet-framework/blob/master/frontend/components/dropdown/dropdown.tpl#L12 (нет mods)
Ниже идет использование ``$smarty.local.text`` хотя это переменная задается выше из локальных.
Предполагаю, что такая неразбериха встречается во многих компонентах.

**Comment by psnet** [comment]
А вот если сделать https://github.com/livestreet/livestreet-framework/issues/143#issuecomment-111702068 то такие ситуации ловить будет проще
