### ISSUE TITLE
js uploader

### ISSUE THREAD

**Issue by mzhelskiy** [livestreet/livestreet-framework#126]
Здесь https://github.com/livestreet/livestreet-framework/blob/master/frontend/components/uploader/js/uploader.js#L134-L155  все ок с this и биндами?

**Comment by deniart** [comment]
Вроде все норм, this там автоматом биндится к коллбэку. Что-то не работает?

**Comment by mzhelskiy** [comment]
просто редактор выдал замечание по синтаксису
ок
