### ISSUE TITLE
Добавить DKIM в отправку писем

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet-framework#127]
Не плохо бы добавить возможность добавлять к письмам подпись, чтобы реже в спам попадали.
В PhpMailer есть все средства, достаточно добавить 4 строчки
```php
$this->oMailer->DKIM_domain = 'имядомена.ру';
$this->oMailer->DKIM_selector = 'mail'; // здесь как прописали в DNS селектор, возможно тоже в конфиг, либо по умолчанию значение, яндекс такое предлагает, может проще в DNS пусть прописывают
$this->oMailer->DKIM_private = 'в конфиге сделать путь до приватного ключа подписи';
$this->oMailer->DKIM_identifier = $this->sFrom;
```

Проверял работает и подписывается и письма перестали в спам идти.
В PhpMailer проверка если хоть одно поле не заполнено, он ничего не делает с DKIM так, что если что то не заполнить проблем не возникнет.

**Comment by lifecom** [comment]
Т.е. в этом случае соответствующая запись в DNS не нужна?

**Comment by venticello** [comment]
Нужна, в DNS записи содержится открытый ключ, которым google, yandex и т.п. проверяют подлинность письма. Тут приведет пример как все исходящие письма livestreet можно подписывать, чтобы они проходили проверку подлинности.
