### ISSUE TITLE
Переделать модуль Text

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#141]
1. В связи с большим количеством внешне вставляемых данных, которые пользователи хотели бы вставлять в топики, для удобного расширения возможностей предлагаю вынести из модуля текста в отдельный модуль методы парсинга видео (VideoParser) https://github.com/livestreet/livestreet-framework/blob/master/classes/modules/text/Text.class.php#L183-L231 , параметров флеш плееров (FlashParamParser) https://github.com/livestreet/livestreet-framework/blob/master/classes/modules/text/Text.class.php#L251-L292 и подстветки кода (CodeSourceParser) https://github.com/livestreet/livestreet-framework/blob/master/classes/modules/text/Text.class.php#L294-L307.

Сделать это нужно для того, чтобы сам модуль отвечающий за обработку текста не обрастал вторичными функциями.

**Comment by venticello** [comment]
После изменений не парсит видео из ВКонтакте.

**Comment by mzhelskiy** [comment]
А там была какая-то проблема с токеном, который нельзя получить из ссылки на видео. Если только саму ссылку копировать прямо из фрейма с этим токеном. Поэтому убрал его.

**Comment by venticello** [comment]
Тогда по сути нужно разрешить в jevix вставлять фреймы vk.com иначе после обновления многие сайты не смогут работать как раньше.
