### ISSUE TITLE
Доработать smarty.local

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#143]
Необходимо доработать функционал `smarty.local` для того, чтобы данный вызов возвращал массив всех локальных переменных переданных в подключаемый шаблон.

Таким образом удастся избежать полного дублирования набора передаваемых переменных при создании локальных копий в компонентах:
```php
{* Генерируем копии локальных переменных, *}
{* чтобы их можно было изменять в дочерних шаблонах *}
{foreach [ 'topic', 'isPreview', 'isList', 'mods', 'classes', 'attributes' ] as $param}
    {assign var="$param" value=$smarty.local.$param}
{/foreach}
```
Таким образом:
```php
{* Генерируем копии локальных переменных, *}
{* чтобы их можно было изменять в дочерних шаблонах *}
{foreach $smarty.local as $param}
    {assign var="$param" value=$smarty.local.$param}
{/foreach}
```
Более того - при таком подходе можно этот общий и теперь стандартный код внести под смарти-функцию, например, `assign_locals` и вызывать в каждом компоненте:
```php
{* Генерируем копии локальных переменных, *}
{* чтобы их можно было изменять в дочерних шаблонах *}
{assign_locals}
```
Также это исключает вероятность в будущем "забыть" один из локальных параметров и не беспокоится о их назначении.

**Comment by deniart** [comment]
Согласен, текущий подход немного костыльный, но в предложенном варианте есть одна проблема - в `$smarty.local` будут находится только *переданные* в компонент параметры (что впрочем можно и сейчас реализовать, т.к. у нас есть спец. параметр `$smarty.local.params`), а те параметры которые не были переданны будут браться из глобального нэймспэйса.

Единственный вариант который приходит на ум при котором не надо будет прописывать все параметры - это доработать смарти так, чтобы в компонентах использовались только локальные перменные (т.е. без префикса `$smarty.local`), но тут надо смотреть, можно ли сделать такое в смарти или нет.

**Comment by psnet** [comment]
>Единственный вариант который приходит на ум при котором не надо будет прописывать все параметры - это доработать смарти так, чтобы в компонентах использовались только локальные перменные (т.е. без префикса $smarty.local), но тут надо смотреть, можно ли сделать такое в смарти или нет.

Можно, в плагин смарти "компонент" нужно добавить три строчки кода и это позволит исключить все внешние переменные таким образом, что в подключаемом файле (компоненте) будут доступны только переданные этому файлу переменные, а общие глобальные переменные (текущий пользователь, имя экшена/эвента) можно будет добавлять в том же компоненте в качестве стандартных.

При этом можно будет отказаться от `$smarty.local` вообще.

Код
---

Для этого нужно модифицировать плагин смарти "компонент" в следующем месте https://github.com/livestreet/livestreet-framework/blob/master/classes/modules/viewer/plugs/function.component.php#L62-L72 так:
```php
/*
 * Сохраняем переменные родителя и очищаем для следующего вызова
 */
$aSavedVars = $oSmarty->tpl_vars;
$oSmarty->tpl_vars = null;

/*
 * Нужно при этом добавить стандартные переменные
 */
$oEngine = Engine::getInstance();
$aComponentParams += array(
  'LIVESTREET_SECURITY_KEY' => $oEngine->Security_GetSecurityKey(),
  'aLang' => $oEngine->Lang_GetLangMsg(),
  'oUserCurrent' => $oEngine->User_GetUserCurrent(),
  'sAction' => Router::GetAction(),
  'sEvent' => Router::GetActionEvent(),
);

/*
 * Получаем путь до шаблона
 */
if ($sPathTemplate = Engine::getInstance()->Component_GetTemplatePath($sName, $sTemplate) and Engine::getInstance()->Viewer_TemplateExists($sPathTemplate)) {
    $sResult = $oSmarty->getSubTemplate($sPathTemplate, $oSmarty->cache_id, $oSmarty->compile_id, null, null, $aComponentParams, Smarty::SCOPE_LOCAL);
} else {
    $sResult = 'Component template not found: ' . $sName . '/' . ($sTemplate ? $sTemplate : $sName) . '.tpl';
}

/*
 * Восстанавливаем переменные
 */
$oSmarty->tpl_vars = $aSavedVars;

```

**Comment by deniart** [comment]
Отлично :+1:  Если никаких конфликтов с текущим функционалом (глобальными переменными) не возникнет, то в ближайшее время реализуем.

**Comment by psnet** [comment]
Я Максиму это уже предлагал, он сказал что иногда внешние переменные нужны и на этом обсуждение закончили.

Но это же мы делаем именно для компонентов, а не для всех инклудов и для них можно назначить ровно то, что нужно.

**Comment by mzhelskiy** [comment]
Я все-таки склоняюсь к перечислению в компоненте списка всех доступных параметром, например, в переменной ``$_component_params`` и последующим вызовом плагина типа ``{assign_locals $_component_params}``. Так мы не отключаем глобальное пространство переменных и документируем список возможных переменных в компоненте.

**Comment by psnet** [comment]
Документация необходимых переменных - само собой, но нужны ли **все** глобальные переменные и эта *возня* с .local?

Пусть компонент живет в своем собственном мире и набором только тех переменных, которые нужны для его работы.

>Я все-таки склоняюсь к перечислению в компоненте списка всех доступных параметром, 

Именно из-за перечисления имен переменных я и предлагаю переделать этот момент т.к. можно что-то забыть в перечислении, более того - это все же лишняя работа.

Резюмируя
---

Предложенный мною код https://github.com/livestreet/livestreet-framework/issues/143#issuecomment-111702068
- позволит избавится вообще в компонентах от блоков кода подобных этому:
```php
{* Генерируем копии локальных переменных, *}
{* чтобы их можно было изменять в дочерних шаблонах *}
{foreach [ 'topic', 'isPreview', 'isList', 'mods', 'classes', 'attributes' ] as $param}
    {assign var="$param" value=$smarty.local.$param}
{/foreach}
```
- и необходимости создания любых новых плагинов для смарти
- и у компонентов будет свое личное пространство и переменные не будут иметь префикса `$smarty.local`

Необходимо только внести правки в смарти-плагин компонента

**Comment by mzhelskiy** [comment]
Добавил плагин смарти "component_define_params"
```
{component_define_params params=['var1','var2','var3','var4','var5']}
```
вместо 
```
{* Генерируем копии локальных переменных, *}
{* чтобы их можно было изменять в дочерних шаблонах *}
{foreach [ 'var1', 'var2', 'var3', 'var4', 'var5'] as $param}
    {assign var="$param" value=$smarty.local.$param}
{/foreach}
```
