### ISSUE TITLE
Доработать гео поле (компонент "поле")

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#144]
Дело в том, что данный тип поля весьма ограничен, в общих чертах он удобен, но сделать что-то более сложное на нём уже затруднительно.

- Нужно дать возможность задавать полное имя для `name` каждого из селектов в т.ч. чтобы это мог быть массив (`filter[city]`)
- Нужно дать возможность задавать классы селектам

**Comment by deniart** [comment]
> Нужно дать возможность задавать полное имя для name каждого из селектов в т.ч. чтобы это мог быть массив (filter[city])

Указывать имя для каждого инпута мне кажется не лучшей идеей, может лучше просто изменить формат name на массив `filter[city]` вместо `filter_city` ?

> Нужно дать возможность задавать классы селектам

Опять же, не хочется плодить доп. параметры, у инпутов, если что, есть уникальные классы на которые можно повесить обработчики (предварительно добавив промежуточный класс основному блоку, например: `.js-my-geo-field .ls-field-geo-city`).

**Comment by psnet** [comment]
>Указывать имя для каждого инпута мне кажется не лучшей идеей, может лучше просто изменить формат name на массив filter[city] вместо filter_city ?

не совсем понял, т.е. указывать имя массива, в данном случае `filter`, а ключи будут стандартными (`city` и т.п.)? Можно и так, но, думаю, все же лучше дать больше гибкости сразу, т.к. может быть ситуация что в фильтре уже будут поля `city` занятые другими инпутами. Либо дать возможность задавать любые имена, а по-умолчанию использовать некий стандарт, так, наверное, будет наиболее правильным: те редкие случаи когда нужно задать полное имя воспользуются такой возможностью, а остальные будут использовать значения по-умолчанию.

По поводу классов - наверное можно и так.

**Comment by deniart** [comment]
> т.е. указывать имя массива, в данном случае filter, а ключи будут стандартными (city и т.п.)?

Да, т.е. для данного компонента, параметр `name` будет играть роль префикса для атрибута `name` и по дефолту равно `geo` (`geo[city], ...`), проблем с гибкостью при таком подходе не должно быть.

> Простая задача: сразу несколько пар гео-полей на одной форме и все в filter.

Тут, если правильно понял, можно задать `name="filter[place1..n]"` и у инпутов атрибут name будет соответственно равен `filter[place1..n][country|region|city]`
