### ISSUE TITLE
Поддерживают ли компоненты в именах инпутов массивы?

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#146]
Во всех компонента можно делать атрибут `name` инпутов/селектов и т.п. чтобы это мог быть массив, например, `entity[a][id]` ?

**Comment by mzhelskiy** [comment]
Вроде name везде ведет себя как строка, а значит может быть любым

**Comment by deniart** [comment]
Ты про это https://github.com/livestreet/livestreet-framework/commit/1a1dd8f35d37bebc49a57c9dde464881a5bf4c24 ?

**Comment by psnet** [comment]
Да, только для всех компонентов.

**Comment by psnet** [comment]
Т.е. для всех `name` использовать `{field_get_value form=$_aRequest name=$name}`

**Comment by psnet** [comment]
@mzhelskiy строка - да, но чтобы получить значение из реквеста от такой строки нужно её разобрать и @deniart написал для этого плагин, теперь его бы ещё везде интегрировать.
