### ISSUE TITLE
Перенести основную логику плагина смарти "компонент" в модуль вьюера

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#147]
Перенести основную логику плагина смарти "компонент" в модуль вьюера и оставить в самом плагине смарти только вызов этого метода. Это необходимо если компонент будет подключаться через бекенд в чистом пхп коде, без фетча какого-либо шаблона.

**Comment by mzhelskiy** [comment]
Перенести не получиться, т.к. там по сути нет никакой общей логики. А метод для бэкенда добавил.
