### ISSUE TITLE
Ошибки function.field_get_value

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet-framework#154]
У меня весь лог завален ошибками:
``[2015-08-12 23:18:16] default.WARNING 8555 7f90f8e: E_USER_WARNING: Parameter 'name' or 'form' cannot be empty {"code":512,"message":"Parameter 'name' or 'form' cannot be empty","file":"/var/www/venticello/data/www/site.ru/framework/classes/modules/viewer/plugs/function.field_get_value.php","line":34}``
Эти ошибки идут еще раньше до внесенных сегодня изменений и с ними тоже идут.

**Comment by mzhelskiy** [comment]
Проблема в том, что в field.radio.tpl и field.checkbox.tpl переменной $form (кстати, она не локальная) может не быть. Там же может не быть и $name, если мы добавляем поле, например, для js.
По хорошему field_get_value не должен выбрасывать ошибку, а просто возвращать пустой результат. И в нем же обращение к ``$aForm[$sName]`` происходит без проверки на isset

**Comment by mzhelskiy** [comment]
А с переменной $form, например, в field.checkbox.tpl как быть?

**Comment by deniart** [comment]
Она берется из field.tpl

**Comment by mzhelskiy** [comment]
Тогда почему ошибку в лог валило, если в field.tpl $form всегда определена?

**Comment by deniart** [comment]
$name не всегда определена

**Comment by mzhelskiy** [comment]
```
{component 'field' template='checkbox'
        name    = 'topic[topic_forbid_comment]'
        checked = {( $topic && $topic->getForbidComment() ) ? true : false }
        note    = $aLang.topic.add.fields.forbid_comments.note
        label   = $aLang.topic.add.fields.forbid_comments.label}
```
вот этот код валил ошибку, здесь $name передается
попробуй откатить изменения в плагине смарти и проверить

**Comment by deniart** [comment]
@mzhelskiy не получилось повторить

**Comment by mzhelskiy** [comment]
Для воспроизведения: 
1. сюда https://github.com/livestreet/livestreet-framework/blob/master/classes/modules/viewer/plugs/function.field_get_value.php в верх добавляем код:
```
if (empty($aParams['name']) || empty($aParams['form'])) {
                trigger_error("Parameter 'name' or 'form' cannot be empty", E_USER_WARNING);
                return;
    }
```
2. заходим на страницу создания топика - в лог начинает сыпаться такое http://take.ms/vUvCx

**Comment by deniart** [comment]
Не получилось, по идеи не должно быть ошибки, name и form определены же, что выводит `{var_dump($form, $name)}` если поставить его перед https://github.com/livestreet/livestreet-framework/blob/master/frontend/components/field/field.checkbox.tpl#L13 ?

**Comment by mzhelskiy** [comment]
Версия PHP у тебя какая?

**Comment by deniart** [comment]
5.4.25

**Comment by mzhelskiy** [comment]
Проблема в том, что при пустом реквесте ``empty($aParams['form'])`` возвращает ``true``, т.к. ``$aParams['form'] = array()``, почему этот код у тебя возвращает ``false`` не понятно.

**Comment by deniart** [comment]
У меня реквест не пустой `{var_dump($_aRequest)}`:
```
array(2) {
    ["PHPSESSID"] => string(32) "6c5f064fd25d930b2edabf589d554cc3"
    ["media_target_tmp_topic"] => string(10) "2eb7882c2f"
}
```

**Comment by mzhelskiy** [comment]
Он у тебя содержит куки, а их там может и не быть. Это определяет директива request_order в php.ini , по дефолту там нет "C" (куки), убери у себя и проверь.

**Comment by deniart** [comment]
Оказывается она вообще не была у меня определена (использовалось значение `variables_order` судя по докам), установил в `GP` стало сыпать ошибки.
