### ISSUE TITLE
data в инпутах

### ISSUE THREAD

**Issue by mzhelskiy** [livestreet/livestreet-framework#156]
При добавлении data аттрибутов к инпутам зачем то приписывается префикс в виде названия компонента lsfields. В тоже время парслей прописан хардом со своим префиксом, но библиотек рахных много и может потребовать прописать data с нужным префиксом, либо вообще без него.
Причем для одних полей нужно использовать data, для других inputData, делают одно и тоже, а называются по разному.

**Comment by deniart** [comment]
Для data атрибутов без префикса можно использовать параметры attributes и inputAttributes. Подробнее в этом тикете - https://github.com/livestreet/livestreet/issues/539
