### ISSUE TITLE
Предложение по field.image-ajax

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet-framework#179]
Предлагаю сделать, этот компонент-поле не привязанным к созданию превью топика. А сделать действия на выбор фотографии медиа и удалению, которые можно будет вызвать с другими обработчиками при использовании с разными сущностями.
Странно, что это поле находится в фреймворке, а явно ссылается на аякс медиа из application, т.е. используя только фреймворк, я не смогу этим полем пользоваться.

**Comment by deniart** [comment]
Поле не привязано к превью топика и использует компонент uploader из фреймворка, urls для `lsFieldImageAjax` и `lsUploader` при иниц-ии можно указать свои.
