### ISSUE TITLE
Поясните логику checkbox

### ISSUE THREAD

**Issue by venticello** [livestreet/livestreet-framework#180]
Если я значения полей в форму готовлю в $_REQUEST, то у "checkbox" checked = true не работает.

**Comment by deniart** [comment]
Каким массив со значениями выглядит? Чекбокс можно отметить например так:

```smarty
{$_aRequest = [
    my_checkbox => true
]}

{component 'field.checkbox' name='my_checkbox' label = 'Label'}
```

**Comment by venticello** [comment]
Просто раньше я делал прямо в поле
`checked = {( $oItem && $oItem->getVisible() == 1 ) ? true : false}`
а после изменений это не работает, в случае если хоть какие то параметры готовятся в $_REQUEST

**Comment by venticello** [comment]
Кстати, как в ситуации с radio быть? там name один на группу.

**Comment by Xmk** [comment]
На php > 5.5 есть проблема исчезает =)

**Comment by deniart** [comment]
Добавил возможность переопределять параметры формы и обновил док-ию (просмотреть можно с помощью плагина [docs](https://github.com/livestreet/lsplugin-docs/):

https://github.com/livestreet/livestreet-framework/commit/a0b05f8d4fe4021175bcd76ca888b39ac19bf4e2 https://github.com/livestreet/livestreet-framework/commit/f09d70d72fdca60fdc2711612547d66561d02c2a
