### ISSUE TITLE
Component Editor

### ISSUE THREAD

**Issue by Xmk** [livestreet/livestreet-framework#199]
1. Подскажите пожалуйста какой-нибудь метод добавления в редактор типа markUp дополнительных тегов? Я кроме трех-колесного велосипеда ничего не могу придумать.
Он необходим для упрощения жизни разработчикам плагинов и не только. Еще было бы круто переопределять колбэки стандартных тегов (например я хочу вставить красивое модальное окно для добавления ссылки или видео).

> ### 2. Компонент **media** не входит в состав фреймворка, но активно используется компонентом **editor**.
> Т.е. пока не вырежешь всё что связано с **media**, **editor** без ошибок не поюзаешь. (либо наоборот, пока не подключишь media)
> Может перенести **media** во фреймворк? Либо подключать его непосредственно из CMS (вместе с кнопочкой редактора).
> При подключении редактора в темплейт модального окна, который мы затем подгружаем через ajax - компонент **media** не инициализируется т.к. его модалка подключается в темплейте редактора в переменную базового лейаута (которой в данной ситуации не существует).
> Предлагаю пересмотреть инициализацию **media**. Например, загружать модалку на всех страницах и инициализировать ее 1 раз. А при обращении к **media** редактора - передавать ему параметры активного поля (**mediaTargetId**, id редактора и прочее). Ну а из медиа уже передавать в **uploader**! (параметры ведь можно переопределять?)
> Это так же сократит количество модальных окон **media** до 1 при любом количестве редакторов на странице.

3. Предлагаю добавить авто-инициализацию редактора при загрузке модалки посредством ajax
Для себя решил это вот таким способом:
```
	$('.js-modal-toggle-default').lsModalToggle({
		show: function(event, data) {
			$('.js-editor-default', data.element).lsEditor();
		}
	});
```
Не первая необходимость, но удобно.

**Comment by deniart** [comment]
1. Можно попробовать мод-ать опции (до dom ready) через прототип виджета `$.livestreet.lsEditorMarkup.prototype.options.sets`
2. Перенес
3. Лучше иниц-ать только когда нужно

**Comment by Xmk** [comment]
2) Модуль и экшн запросы остались в приложении? 

теперь смотри, а что если просто усовершенствовать компонент editor.
media можно оставить в приложении, которая будет добавлять кнопку в редактор со своим функционалом.
так же допустим я напишу компонент спойлера, который при инициализации будет добавлять кнопку в редактор со своим функционалом.

**Comment by deniart** [comment]
> Модуль и экшн запросы остались в приложении?

Да

Идея с добавленим кнопки хорошая, но оставим это для след. версий, сейчас это не критично

**Comment by Xmk** [comment]
переноси тогда media обратно в приложение)) я подумаю над реализацией на днях, предложу в виде pull request.
Для cms не критично. Мне как разработчику на базе фреймворка критично)

**Comment by Xmk** [comment]
23
