### ISSUE TITLE
SmartyLS

### ISSUE THREAD

**Issue by KarelWintersky** [livestreet/livestreet-framework#241]
https://github.com/livestreet/livestreet-framework/blob/f0d3f5ddf0266e408d86db15d2e7514cee9d4e99/libs/application/SmartyLS/smarty_internal_template_ls.php

Зачем нужен этот класс и что делает вот этот код:

```
if (!$bSkipDelegate) {
            $template_resource = Engine::getInstance()->Plugin_GetDelegate('template', $template_resource);
        }
```
В чем его тайный смысл?

**Comment by Xmk** [comment]
@KarelWintersky класс нужен для обработки наследования шаблонов компонентов. Вот этот код получает шаблон с учетом переопределения (например плагинами)

**Comment by KarelWintersky** [comment]
Я так и думал, спасибо. 

Если плагины не используются совсем и выпилены из движка как класс (например, на табуне) - можем ли мы отказаться от этого _расширения_ и использовать стандартный смарти?

**Comment by Xmk** [comment]
@KarelWintersky ты можешь делать с движком всё что заблагорассудится. Но обрати внимания что файл обрабатывает компоненты, а не плагины.

Чтобы отказаться от этого "расширения" и юзать стандартный смарти достаточно вот тут:
https://github.com/livestreet/livestreet-framework/blob/6e5b02b5a30c8eab435fe77b032c6a4f59a68a3b/classes/modules/viewer/Viewer.class.php#L345
заменить **SmartyLS** на **Smarty**

**Comment by KarelWintersky** [comment]
У нас 1.0 ветка ;-)

Впрочем... насколько сильно изменилась БД в версии 2.0 по сравнению с БД 1.0
Топики, комментарии? 
Были ли критичные изменения, которые не позволят "просто обновить кодовую базу" и использовать 2.0 ?

**Comment by Xmk** [comment]
@KarelWintersky 
обновлял и не единожды "кодовую базу" движка не меняя структуру бд, ничего сложно если понимаешь что делаешь

**Comment by KarelWintersky** [comment]
Ясно, спасибо.
