### ISSUE TITLE
Расширение передачи данных при загрузке модального окна через ajax

### ISSUE THREAD

**Issue by kerbylav** [livestreet/livestreet-framework#45]
Было бы не плохо добавить возможность передавать через ajax значения полей из какой-то формы при загрузке модального окна через ajax типа:

```html
<button type="submit" class="button button-primary" data-type='modal-toggle' data-modal-url='{router page='...'}' data-paramform='#formId'>Далее...</button>
```

**Comment by deniart** [comment]
Функционал довольно специфичный для включения его в modal.

**Comment by kerbylav** [comment]
Ну как "специфичный"... Но... Давно не смотрел в код - есть ли возможность передать какие-то параметры при загрузке модального окна через data-type='modal-toggle'?

**Comment by kerbylav** [comment]
Типа

```html
<button type="submit" class="button button-primary" data-type='modal-toggle' data-modal-url='{router page='...'}' data-param-id='1' data-param-content-type='topic'>Редактировать...</button>
```

Чтобы в ajax-запрос "примешались" два параметра - id и contentType

**Comment by mzhelskiy** [comment]
@kerbylav  именно так и работает

**Comment by kerbylav** [comment]
@mzhelskiy А, ну тогда прекрасно!
