### ISSUE TITLE
Два notice-уведомления 

### ISSUE THREAD

**Issue by Chiliec** [livestreet/livestreet-framework#74]
При нажатии на кнопку "подписаться" в топике показываются два уведомления:
![notice](https://cloud.githubusercontent.com/assets/982358/6202966/fc0e3d44-b528-11e4-9306-79fbd4191e67.png)
Вроде вычислил что эта строчка так делает: https://github.com/livestreet/livestreet-framework/blob/master/frontend/components/ls-core/ajax.js#L49

**Comment by mzhelskiy** [comment]
Здесь просто в ls скриптах нужно убрать вызов сообщения.
Там еще нужна опция "не показывать сообщения" даже когда они есть в ответе.

**Comment by deniart** [comment]
Поправил https://github.com/livestreet/livestreet/commit/3e72059946eb2d902a9a80955f1cfe208f83ed79 https://github.com/livestreet/livestreet-framework/commit/dae4ad3c41abfd9224c44ad9fcc8134815c70ec5
