### ISSUE TITLE
Переделать логику получения имени таблицы для плагина для ОРМ

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#83]
Сейчас для использования имени плагина как префикса для его таблиц в орм нужно обязательно указывать соответствие этой таблицы в конфиге (см. https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/MapperORM.class.php#L650-L659 в ```public static function GetTableName($oEntity)```)
```php
if ($sPluginName) {
    $sTablePlugin = $sPluginName . '_' . $sTable;
    /**
     * Для обратной совместимости с 1.0.1
     * Если такая таблица определена в конфиге, то ок, если нет, то используем старый вариант без имени плагина
     */
    if (Config::Get('db.table.' . $sTablePlugin)) {
        $sTable = $sTablePlugin;
    }
}
```
Так вот, *это не дело*. **Нужно стандартизировать все это и чтобы таблицы плагинов по-умолчанию имели префикс имени плагина.**
- Это однозначно. Всегда в БД видно какие таблицы к чему относятся: к движку или к какому-то конкретному плагину, а не каша из разных таблиц и *начинай* сравнивать с дампом движка чтобы вспомнить все его таблицы или понять какого плагина конкретная таблица, если она была создана без префикса.
- Убирается обязательная запись для этого в конфиге плагина (не нужно для каждой новой таблицы бегать в конфиг и прописывать)

Поэтому вышеприведенный кусок кода нужно заменить на:
```php
$sTable = $sPluginName ? $sPluginName . '_' . $sTable : $sTable;
```

также можно сравнение ```if (strpos($sEntityName, $sModuleName) === 0) {``` на равенство перевести https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/MapperORM.class.php#L645

**Comment by mzhelskiy** [comment]
Случаи бывают разные, это нужно регламентировать гайдами, а не жестко в коде.

**Comment by psnet** [comment]
Нет, тут как раз костыль от 1.0.1. **Не могут** (читать "не должны") плагины именовать свои таблицы без префикса. Единственный случай (только что придумал) - если плагин захочет работать с таблицей **движка** (для чтения, например,) средствами ОРМ. Вот нужно подумать.

**Comment by psnet** [comment]
А есть решение и для вышеуказанной задачи - плагин сможет сделать алиас т.к. название таблицы можно переопределить в конфиге.
https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/MapperORM.class.php#L663-L664

**Comment by mzhelskiy** [comment]
Почему то решил, что ты хочешь вообще убрать возможность задавать таблицу через конфиг и сделать только жесткую привязку к плагин-модуль-сущность.
ок

**Comment by psnet** [comment]
Т.е. иными словами - **инвертировать текущую логику** с таблицами:

Сейчас
---

- чтобы сделать **таблицу с префиксом** имени плагина - это **нужно прописать в конфиге**

Если внести правки выше
---

- **по-умолчанию** будет использоваться **таблица с префиксом** и не нужно будет это прописывать в конфиге
- а если нужно будет задать **другое полное имя таблицы** - тогда это можно и **прописать в конфиге** плагина

Т.е. текущая функциональность не меняется и не урезается, а лишь меняется подход по-умолчанию, который используется в большинстве случаев.

**Comment by psnet** [comment]
>Почему то решил, что ты хочешь вообще убрать возможность задавать таблицу через конфиг и сделать только жесткую привязку к плагин-модуль-сущность.

Нет, только сделать это по-умолчанию, т.к. сейчас это для плагинов просто "модуль-сущность".

Надеюсь объяснил.
