### ISSUE TITLE
При инсталяции лс в конфиге автоматически генерировать примесь для ключа безопасности

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#85]
Устанавливать случайное значение при инсталяции лс:
```php
$config['module']['security']['hash']  = "livestreet_security_key"; // "примесь" к строке, хешируемой в качестве security-кода
```
https://github.com/livestreet/livestreet-framework/blob/master/config/config.php#L311

**Comment by Chiliec** [comment]
Отличная идея! В Yii2 так и происходит, но только при установке через Composer...

**Comment by psnet** [comment]
Вот и лс вырос и старые штанишки ему жмут, нужно сделать *как взрослых дядей*!

**Comment by Chiliec** [comment]
Иронию граничущую с троллингом оценил, но мне действительно интересно как это реализовать грамотно. Что-то делать с config-файлом из установщика как-то не очень хорошая идея. Я вот думаю прямо в конфиге взять какие-нибудь параметры сервера, которые нельзя узнать извне. Сложить несколько таких параметров в строку, хешануть — и `livestreet_security_key` готов. Проблема с ручным заполнением решена. Ну как вариант :wheelchair:

**Comment by psnet** [comment]
>Иронию граничущую с троллингом оценил

Почему ирония с тролингом? Нет такого. Это обычная безобидна шутка :+1: 

>Что-то делать с config-файлом из установщика как-то не очень хорошая идея.

А он так именно и делает :smile:

**Comment by Chiliec** [comment]
>Почему ирония с тролингом? Нет такого. Это обычная безличностная безобидна шутка :+1:

Ну ладно тогда :octocat: 

>А он так именно и делает :smile:

Тогда действительно не понятно почему этого до сих пор нет :confused:
