### ISSUE TITLE
Лишняя логика в Security.class.php

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#86]
В методе ```public function ValidateSendForm($bDie = true)``` параметр ```$bDie``` не нужен т.к. есть метод ```ValidateSecurityKey``` и при ```$bDie = false``` выходит что ```ValidateSendForm``` является прямой оберткой над ```ValidateSecurityKey``` и только путает. Нужно оставить как и было в ранних версиях только
```php
die("Hacking attemp!");
```
и параметр убрать вовсе.
https://github.com/livestreet/livestreet-framework/blob/master/classes/modules/security/Security.class.php#L57

**Comment by mzhelskiy** [comment]
ValidateSendForm - это мета-метод, который по дефолту сейчас использует только один метод, но может больше.

**Comment by psnet** [comment]
>ValidateSendForm - это мета-метод

имеешь ввиду враппер?

>который по дефолту сейчас использует только один метод, но может больше.

Покажите примеры когда необходимо "больше"? Сейчас это лишняя путаница.

**Comment by mzhelskiy** [comment]
При проверке отправки формы не нужно знать, как именно она проверяется (сверка csrf токена или другая логика), достаточно знать один метод для ее проверки ValidateSendForm.
Далее логика может меняться не затрагиваю код приложения (как минимум по части бэкенда).

**Comment by psnet** [comment]
Вот прав теоретически, но я практически не могу предположить что нужно добавить ещё именно для проверки безопасности формы.
