### ISSUE TITLE
Тип инпута translit

### ISSUE THREAD

**Issue by prokopov-nikolai** [livestreet/livestreet-framework#9]
При создание блогов не дает возможность ставить дефис.
<b>Решение</b>
В файле /framework/frontend/framework/js/vendor/parsley/parsley.js<br>
после 103 строки добавил<br>
<pre class="prettyprint"><span class="kwd">case</span><span class="pln"> </span><span class="str">'translit'</span><span class="pun">:</span><span class="pln">
            regExp </span><span class="pun">=</span><span class="pln"> </span><span class="str">/^[a-z0-9-_]+$/</span><span class="pun">;</span></pre><br>
в файле /application/frontend/skin/developer/actions/ActionBlog/add.tpl<br>
в строке 43 поменял тип alphanum на translit<br>
<pre class="prettyprint"><span class="pln">sFieldRules      </span><span class="pun">=</span><span class="pln"> </span><span class="str">'required="true" type="translit" rangelength="[2,50]"'</span></pre>
http://livestreet.ru/blog/dev_livestreet/16567.html#comment267259

**Comment by Chiliec** [comment]
По-моему можно закрывать, дефис ставится.
