### ISSUE TITLE
Доработать "Необходимость генерации автоматических хуков"

### ISSUE THREAD

**Issue by psnet** [livestreet/livestreet-framework#92]
Уже сделано
---
В ```public function _CallModule($sName, $aArgs)``` (Engine.class.php) используется проверка на необходимость генерации автоматических хуков:
```php
/**
* Необходимость генерации автоматических хуков
*/
$bUseAutoHooks = (bool)Config::Get('sys.module.use_auto_hooks');
```
https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/Engine.class.php#L578

(Параметр в конфиге https://github.com/livestreet/livestreet-framework/blob/master/config/config.php#L101-L104)

Ещё в движке
---

Но кроме этого автохуки ещё запускаются в ```protected function InitModule($oModule, $bHookParent = true)``` (https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/Engine.class.php#L328)

Вот здесь https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/Engine.class.php#L354
И здесь https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/Engine.class.php#L359

Это не так критично как в _CallModule т.к. здесь они запускаются один раз при инициализации, но как оптимизация имеет место жить (модули движка + всех плагинов делают два вызова хука при своей инициализации каждый)

Ещё в экшенах
---

Также автогенерируемые хуки есть и в экшенах. В ```public function ExecEvent()``` Action.class.php

Один https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/Action.class.php#L256
Два https://github.com/livestreet/livestreet-framework/blob/master/classes/engine/Action.class.php#L275

**Comment by mzhelskiy** [comment]
Эти хуки довольно полезны и позволяют не увеличивать цепочки наследования классов.
