### ISSUE TITLE
Доработка ORM

### ISSUE THREAD

**Issue by prokopov-nikolai** [livestreet/livestreet-framework#95]
$aFilter = array(
	'#select' => array(" t.*, COUNT(*) as `count`, DATE_FORMAT(t.date_add, '%Y') as year"),
	'#order' => array('year' => 'desc'),
	'#group' => array('year')
);

Сейчас не возможно сгруппировать по дополнительному полю "year" и по нему же отсортировать.
В запрос подставляется "t."

**Comment by kerbylav** [comment]
На мой взгляд, откровенно говоря, это уже далеко за гранью ORM. ORM должна работать с сущностями, объектами (или МАКСИМУМ с какими-то полями сущности, что бывает полезно), а то, что тут представлено... почему бы не использовать традиционный подход?

**Comment by prokopov-nikolai** [comment]
Я не предлагаю добавления никакого нового функционала, а лишь по возможности прошу добавить проверку на подстановку "t.". Подставлять ее только в том случае если поле из "#order или #group есть в таблице, в противном случае не добавлять.

**Comment by kerbylav** [comment]
Ну там с алиасами вообще ряд нюансов, да. Включая попытки сортировки по полю из #join. Поэтому я бы вообще отменил добавление алиаса в #group и #order - пусть это будет на совести разработчика.

**Comment by kerbylav** [comment]
@prokopov-nikolai кстати, для order Максим делал фикс по моей просьбе https://github.com/livestreet/livestreet-framework/commit/1e41ee8a25540dfb3ce8749a31f9c05baca21a72

@mzhelskiy Такое же видимо надо для #group сделать

**Comment by psnet** [comment]
@kerbylav можешь объяснить что это и для чего:
``php
'#order'=>array(
 '#(t.sort+s.sort*10000)'=>'asc'
)
```
?

**Comment by kerbylav** [comment]
@psnet Да это просто тупой пример, главное, чтобы содержимое не трогалось

**Comment by psnet** [comment]
@kerbylav чего же ты так пугаешь-то? :smiling_imp: я все пытался понять тайный смысл
